import bundleImg from './assets/bundle_main.png';
import bundleGaming from './assets/bundle_gaming.png';
import bundleAnime from './assets/bundle_anime.png';
import bundleBusiness from './assets/bundle_business.png';
import bundleSpirit from './assets/bundle_spirit.png';
import bundleAesthetic from './assets/bundle_aesthetic.png';
import infosysImg from './assets/infosys_logo.png';
import jpmorganImg from './assets/jpmorgan_logo.png';

const sIcon = (slug, color='fff') => `<img src="https://cdn.simpleicons.org/${slug}/${color}" style="width:100%;height:100%;object-fit:contain;padding:4px;box-sizing:border-box;filter:drop-shadow(0 2px 8px rgba(0,0,0,0.5));" onerror="this.style.display='none'" />`;
const iconImg = (domain) => `<img src="https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://${domain}&size=128" style="width:100%;height:100%;object-fit:contain;border-radius:50%;background:#fff;padding:4px;box-sizing:border-box;" onerror="this.src='https://ui-avatars.com/api/?name=${domain.split('.')[0]}&background=random'"/>`;
const i8 = (name) => `<img src="https://img.icons8.com/color/256/${name}.png" style="width:100%;height:100%;object-fit:contain;padding:4px;box-sizing:border-box;"/>`;
const cdnImg = (url) => `<img src="${url}" style="width:100%;height:100%;object-fit:cover;border-radius:12px;" />`;

export const brandIcons = {
  netflix: i8('netflix'),
  spotify: i8('spotify'),
  prime: i8('amazon-prime-video'),
  hotstar: iconImg('hotstar.com'),
  combo: i8('product'),
  youtube: iconImg('youtube.com'),
  chatgpt: i8('chatgpt'),
  perplexity: sIcon('perplexity', '22B8CD'),
  claude: sIcon('anthropic','D4A27F'),
  midjourney: iconImg('midjourney.com'),
  gemini: iconImg('gemini.google.com'),
  deepl: iconImg('deepl.com'),
  microsoft: i8('microsoft'),
  autodesk: i8('autodesk'),
  capcut: iconImg('capcut.com'),
  supergrok: sIcon('x', 'fff'),
  windsurf: iconImg('codeium.com'),
  freepik: sIcon('freepik', '1273EB'),
  envato: sIcon('envato', '81B441'),
  quillbot: iconImg('quillbot.com'),
  openart: iconImg('openart.ai'),
  higgsfield: iconImg('higgsfield.ai'),
  lovable: iconImg('lovable.dev'),
  nordvpn: i8('nordvpn'),
  canva: i8('canva'),
  notion: i8('notion'),
  figma: i8('figma'),
  bolt: iconImg('bolt.new'),
  lenskart: iconImg('lenskart.com'),
  coursera: iconImg('coursera.org'),
  jarvis: iconImg('jasper.ai'),
  blackbox: iconImg('blackbox.ai'),
  gamma: iconImg('gamma.app'),
  filmora: iconImg('filmora.wondershare.com'),
  beautifulai: iconImg('beautiful.ai'),
  infosys: `<img src="${infosysImg}" style="width:100%;height:100%;object-fit:contain;border-radius:50%;background:rgba(255,255,255,0.05);padding:2px;box-sizing:border-box;" />`,
  jpmorgan: `<img src="${jpmorganImg}" style="width:100%;height:100%;object-fit:contain;border-radius:50%;background:rgba(255,255,255,0.05);padding:2px;box-sizing:border-box;" />`,
  pocketfm: iconImg('pocketfm.com'),
  instagram: i8('instagram'),
  reels: `<img src="https://img.icons8.com/fluency/256/instagram-reel.png" style="width:100%;height:100%;object-fit:contain;padding:2px;box-sizing:border-box;"/>`,
  shopify: i8('shopify'),
  heygen: iconImg('heygen.com'),
  expressvpn: iconImg('expressvpn.com'),
  grammarly: iconImg('grammarly.com'),
  elevenlabs: iconImg('elevenlabs.io'),
  replit: iconImg('replit.com'),
  windows11: i8('windows-11'),
  // Digital Bundle images from c36india CDN
  // Digital Bundle images - Specific Category Replacements
  'bundle-dancing': cdnImg(bundleSpirit),
  'bundle-hulk': cdnImg(bundleGaming),
  'bundle-monkey': cdnImg(bundleSpirit),
  'bundle-shopify': cdnImg(bundleBusiness),
  'bundle-ben10': cdnImg(bundleAnime),
  'bundle-oggy': cdnImg(bundleAnime),
  'bundle-mrbean': cdnImg(bundleSpirit),
  'bundle-doraemon': cdnImg(bundleAnime),
  'bundle-freefire': cdnImg(bundleGaming),
  'bundle-motivation': cdnImg(bundleSpirit),
  'bundle-anime': cdnImg(bundleAnime),
  'bundle-sinchan': cdnImg(bundleAnime),
  'bundle-darkpsych': cdnImg(bundleBusiness),
  'bundle-ebooks': cdnImg(bundleBusiness),
  'bundle-aesthetic': cdnImg(bundleAesthetic),
  'bundle-krishna': cdnImg(bundleSpirit),
  'bundle-creators': cdnImg(bundleBusiness),
  'bundle-podcast': cdnImg(bundleSpirit),
  'bundle-space': cdnImg(bundleAesthetic),
  'bundle-f1': cdnImg(bundleAesthetic),
  'bundle-gym': cdnImg(bundleGaming),
  'bundle-emotional': cdnImg(bundleSpirit),
  'cb-bundle-0': `<img src="/bundles/cb-bundle-0.webp" style="width:100%;height:100%;object-fit:cover;border-radius:12px;" />`,
  'cb-bundle-1': `<img src="/bundles/cb-bundle-1.webp" style="width:100%;height:100%;object-fit:cover;border-radius:12px;" />`,
  'cb-bundle-2': `<img src="/bundles/cb-bundle-2.webp" style="width:100%;height:100%;object-fit:cover;border-radius:12px;" />`,
  'cb-bundle-3': `<img src="/bundles/cb-bundle-3.webp" style="width:100%;height:100%;object-fit:cover;border-radius:12px;" />`,
  'cb-bundle-4': `<img src="/bundles/cb-bundle-4.webp" style="width:100%;height:100%;object-fit:cover;border-radius:12px;" />`,
  'cb-bundle-5': `<img src="/bundles/cb-bundle-5.webp" style="width:100%;height:100%;object-fit:cover;border-radius:12px;" />`,
  'cb-bundle-6': `<img src="/bundles/cb-bundle-6.webp" style="width:100%;height:100%;object-fit:cover;border-radius:12px;" />`,
  'cb-bundle-7': `<img src="/bundles/cb-bundle-7.webp" style="width:100%;height:100%;object-fit:cover;border-radius:12px;" />`,
  'cb-bundle-8': `<img src="/bundles/cb-bundle-8.webp" style="width:100%;height:100%;object-fit:cover;border-radius:12px;" />`,
  'cb-bundle-9': `<img src="/bundles/cb-bundle-9.webp" style="width:100%;height:100%;object-fit:cover;border-radius:12px;" />`,
  'cb-bundle-10': `<img src="/bundles/cb-bundle-10.webp" style="width:100%;height:100%;object-fit:cover;border-radius:12px;" />`,
  'cb-bundle-11': `<img src="/bundles/cb-bundle-11.webp" style="width:100%;height:100%;object-fit:cover;border-radius:12px;" />`,
  'cb-bundle-12': `<img src="/bundles/cb-bundle-12.webp" style="width:100%;height:100%;object-fit:cover;border-radius:12px;" />`,
  'cb-bundle-13': `<img src="/bundles/cb-bundle-13.webp" style="width:100%;height:100%;object-fit:cover;border-radius:12px;" />`,
  bundle: cdnImg(bundleImg)
};

export const products = [
  // --- AI Tools ---
  {id:'chatgpt-plus',name:'ChatGPT Plus',cat:'AI Tools',mrp:'₹2,000',discount:'73%',icon:'chatgpt',tag:'Trending',color:'#10A37F',
    desc:'ChatGPT Plus with GPT-4o and GPT 5.5 access, faster response times, priority access.', features:['GPT-4o / 5.5 access','Faster responses','Image generation'],
    variants: [{name:'1 Month (Shared)', price:'₹200', priceNum:200}, {name:'1 Month (Private)', price:'₹600', priceNum:600}]},
  {id:'perplexity-pro',name:'Perplexity Pro',cat:'AI Tools',mrp:'₹17,000',discount:'82%',icon:'perplexity',tag:'Popular',color:'#22B8CD',
    desc:'Perplexity Pro gives you access to the latest models like GPT-4o and Claude 3.5 Sonnet, plus unlimited Pro searches.', features:['Unlimited Pro searches','GPT-4o & Claude 3.5','API credits'],
    variants: [{name:'1 Year', price:'₹2,999', priceNum:2999}]},
  {id:'claude-pro',name:'Claude AI Pro',cat:'AI Tools',mrp:'₹1,999',discount:'90%',icon:'claude',tag:'New',color:'#D4A27F',
    desc:'Claude AI Pro by Anthropic — advanced reasoning with Claude 3.5 Sonnet.', features:['Claude 3.5 Sonnet','200K context','Artifacts & Projects'],
    variants: [{name:'1 Month', price:'₹1,599', priceNum:1599}]},
  {id:'gemini-pro',name:'Gemini AI Pro Advanced',cat:'AI Tools',mrp:'₹19,999',discount:'90%',icon:'gemini',tag:null,color:'#4285F4',
    desc:'Get Google Gemini AI Pro Advanced with access to the latest 1.5 Pro and 3.1 generation models.', features:['Gemini 3.1 Pro','2TB Storage','Advanced coding'],
    variants: [{name:'18 Months', price:'₹1,999', priceNum:1999}]},
  {id:'midjourney',name:'Midjourney Premium',cat:'AI Tools',mrp:'₹4,999',discount:'90%',icon:'midjourney',tag:'Popular',color:'#000000',
    desc:'Midjourney v6 Premium for stunning AI image generation.', features:['Unlimited generations','Fast mode','High-res export'],
    variants: [{name:'1 Month', price:'₹499', priceNum:499}, {name:'1 Year', price:'₹2,999', priceNum:2999}]},
  {id:'deepl-pro',name:'DeepL Pro',cat:'AI Tools',mrp:'₹1,219',discount:'59%',icon:'deepl',tag:null,color:'#0F2B46',
    desc:'DeepL Pro for ultimate AI-powered translation. Maximum data security.', features:['Unlimited translation','Editable docs','Max security'],
    variants: [{name:'1 Month', price:'₹500', priceNum:500}]},
  {id:'quillbot-premium',name:'Quillbot Premium',cat:'AI Tools',mrp:'₹999',discount:'70%',icon:'quillbot',tag:null,color:'#499557',
    desc:'QuillBot Premium for advanced paraphrasing, grammar checking, and plagiarism detection.', features:['Unlimited words','Advanced grammar','Plagiarism checker'],
    variants: [{name:'1 Month', price:'₹299', priceNum:299}]},
  {id:'openart',name:'OpenArt AI',cat:'AI Tools',mrp:'₹5,299',discount:'54%',icon:'openart',tag:null,color:'#FF5100',
    desc:'OpenArt AI premium access for generating high-quality AI images.', features:['Unlimited generation','High-res export','Premium models'],
    variants: [{name:'Essential (1 Month)', price:'₹749', priceNum:749}, {name:'Infinite (1 Month)', price:'₹3,124', priceNum:3124}, {name:'Advanced (1 Month)', price:'₹4,374', priceNum:4374}]},
  {id:'higgsfield',name:'Higgsfield Ultimate',cat:'AI Tools',mrp:'₹4,999',discount:'68%',icon:'higgsfield',tag:null,color:'#ffffff',
    desc:'Ultimate video generation with Higgsfield AI models.', features:['Video generation','High resolution','Priority processing'],
    variants: [{name:'Ultimate', price:'₹1,919', priceNum:1919}]},
  {id:'jarvis',name:'Jarvis AI (Starter)',cat:'AI Tools',mrp:'₹999',discount:'76%',icon:'jarvis',tag:null,color:'#333333',
    desc:'Jarvis AI Starter Plan for content generation. Private, Ad-Free, Premium Access.', features:['Private Account','Premium Access','Secure Login'],
    variants: [{name:'1 Month', price:'₹239', priceNum:239}]},
  {id:'blackbox',name:'Blackbox AI',cat:'AI Tools',mrp:'₹4,999',discount:'70%',icon:'blackbox',tag:null,color:'#000000',
    desc:'Blackbox AI for ultimate code generation and autocompletion.', features:['Code generation','Repo context','Fast autocomplete'],
    variants: [{name:'1 Year', price:'₹1,899', priceNum:1899}]},
  {id:'gamma',name:'Gamma App Pro',cat:'AI Tools',mrp:'₹999',discount:'80%',icon:'gamma',tag:'Hot Deal',color:'#292929',
    desc:'Gamma Pro for AI-powered presentation generation and document creation.', features:['AI presentations','No watermarks','Premium templates'],
    variants: [{name:'1 Month', price:'₹399', priceNum:399}]},
  {id:'heygen',name:'Heygen AI',cat:'AI Tools',mrp:'₹9,999',discount:'76%',icon:'heygen',tag:'Trending',color:'#7B61FF',
    desc:'Heygen AI Video Creation with Realistic Avatars, Text-to-Video in Multiple Languages.', features:['Realistic Avatars','Lip-sync','Natural Voice Overs'],
    variants: [{name:'1 Month', price:'₹2,399', priceNum:2399}]},
  {id:'elevenlabs',name:'Elevenlabs',cat:'AI Tools',mrp:'₹14,999',discount:'80%',icon:'elevenlabs',tag:null,color:'#000000',
    desc:'Elevenlabs most powerful AI voice generator. One-time payment, activate on your own email.', features:['AI Voice Generator','Own Email Activation','Ideal for Reels'],
    variants: [{name:'3 Months', price:'₹2,999', priceNum:2999}, {name:'1 Year', price:'₹8,999', priceNum:8999}]},
  {id:'grammarly',name:'Grammarly Premium',cat:'AI Tools',mrp:'₹1,999',discount:'76%',icon:'grammarly',tag:null,color:'#15C39A',
    desc:'Grammarly Personal Account. Premium Features, AI Writing Assistant, Plagiarism Checker.', features:['Private Account','Plagiarism Checker','Grammarly Go'],
    variants: [{name:'1 Month', price:'₹479', priceNum:479}]},

  // --- Developer Tools ---
  {id:'supergrok',name:'SuperGrok',cat:'Developer Tools',mrp:'₹999',discount:'80%',icon:'supergrok',tag:'Trending',color:'#000000',
    desc:'Get access to Grok AI. Fast, witty, and powerful AI assistant.', features:['Real-time web access','Unfiltered responses','Coding assistance'],
    variants: [{name:'30 Days', price:'₹399', priceNum:399}]},
  {id:'windsurf',name:'Windsurf',cat:'Developer Tools',mrp:'₹1,885',discount:'76%',icon:'windsurf',tag:null,color:'#09B6A2',
    desc:'Windsurf Editor by Codeium. The ultimate AI-powered IDE.', features:['AI code generation','Instant refactoring','Multi-file chat'],
    variants: [{name:'14 Days', price:'₹450', priceNum:450}]},
  {id:'lovable',name:'Lovable AI Pro',cat:'Developer Tools',mrp:'₹9,999',discount:'80%',icon:'lovable',tag:null,color:'#E04A4A',
    desc:'Lovable AI Pro for generative UI and frontend development.', features:['Generative UI','Export code','React & Tailwind support'],
    variants: [{name:'1 Month', price:'₹2,499', priceNum:2499}]},
  {id:'bolt',name:'Bolt.new Premium',cat:'Developer Tools',mrp:'₹4,999',discount:'80%',icon:'bolt',tag:null,color:'#ffffff',
    desc:'Bolt.new Premium for instant full-stack environment generation.', features:['Full-stack gen','Cloud deployment','Private repos'],
    variants: [{name:'1 Month', price:'₹1,299', priceNum:1299}]},
  {id:'replit',name:'Replit Core',cat:'Developer Tools',mrp:'₹9,999',discount:'58%',icon:'replit',tag:null,color:'#F26207',
    desc:'Replit Core with Ghostwriter AI (autocomplete/bug fixing), Unlimited private Repls.', features:['Ghostwriter AI','Unlimited Private Repls','Custom Domain'],
    variants: [{name:'1 Year', price:'₹4,199', priceNum:4199}]},

  // --- Design Resources ---
  {id:'canva-pro',name:'Canva Pro',cat:'Design Resources',mrp:'₹999',discount:'90%',icon:'canva',tag:'Popular',color:'#00C4CC',
    desc:'Canva Pro / Edu access for premium templates and assets.', features:['Premium templates','Background remover','Pro elements'],
    variants: [{name:'1 Month', price:'₹119', priceNum:119}, {name:'1 Year', price:'₹199', priceNum:199}]},
  {id:'figma-pro',name:'Figma Professional',cat:'Design Resources',mrp:'₹9,999',discount:'80%',icon:'figma',tag:null,color:'#F24E1E',
    desc:'Figma Professional plan for team collaboration and advanced prototyping.', features:['Unlimited projects','Advanced prototyping','Team libraries'],
    variants: [{name:'1 Month', price:'₹2,299', priceNum:2299}]},
  {id:'beautifulai',name:'Beautiful.ai Pro',cat:'Design Resources',mrp:'₹4,999',discount:'80%',icon:'beautifulai',tag:null,color:'#1F4CE0',
    desc:'Beautiful.ai Pro for automated presentation design.', features:['Smart templates','AI presentation builder','Analytics'],
    variants: [{name:'1 Year', price:'₹999', priceNum:999}]},
  {id:'freepik-premium',name:'Freepik Premium',cat:'Design Resources',mrp:'₹16,080',discount:'50%',icon:'freepik',tag:'Popular',color:'#1273EB',
    desc:'Access millions of premium vectors, photos, PSD files.', features:['Unlimited downloads','AI image gen','No attribution'],
    variants: [{name:'1 Month', price:'₹750', priceNum:750}, {name:'3 Months', price:'₹2,000', priceNum:2000}, {name:'6 Months', price:'₹4,000', priceNum:4000}, {name:'12 Months', price:'₹8,000', priceNum:8000}]},
  {id:'envato-elements',name:'Envato Elements',cat:'Design Resources',mrp:'₹4,999',discount:'80%',icon:'envato',tag:'Trending',color:'#81B441',
    desc:'Unlimited downloads of premium graphics, templates on Envato Elements.', features:['Millions of assets','Video templates','Commercial license'],
    variants: [{name:'1 Year', price:'₹999', priceNum:999}]},

  // --- Softwares & Tools ---
  {id:'ms-office-365',name:'Microsoft 365',cat:'Softwares & Tools',mrp:'₹6,899',discount:'86%',icon:'microsoft',tag:'Best Value',color:'#F25022',
    desc:'Microsoft 365 with Word, Excel, PowerPoint, Outlook, OneDrive.', features:['Word, Excel, PowerPoint','1TB OneDrive','5 devices'],
    variants: [{name:'1 Year', price:'₹999', priceNum:999}]},
  {id:'autodesk',name:'Autodesk',cat:'Softwares & Tools',mrp:'₹2,819',discount:'65%',icon:'autodesk',tag:null,color:'#0696D7',
    desc:'Access to Autodesk suite including AutoCAD, Maya, 3ds Max.', features:['AutoCAD & Revit','Maya & 3ds Max','1 year validity'],
    variants: [{name:'1 Year', price:'₹1,599', priceNum:1599}]},
  {id:'capcut-pro',name:'CapCut Pro',cat:'Softwares & Tools',mrp:'₹1,999',discount:'70%',icon:'capcut',tag:null,color:'#000000',
    desc:'CapCut Pro unlocks all premium templates, effects, filters.', features:['No watermark','Pro templates','Cloud storage'],
    variants: [{name:'6 Months', price:'₹349', priceNum:349}, {name:'12 Months', price:'₹599', priceNum:599}]},
  {id:'notion-plus',name:'Notion Plus',cat:'Softwares & Tools',mrp:'₹9,999',discount:'80%',icon:'notion',tag:null,color:'#000000',
    desc:'Notion Plus plan for unlimited blocks and team collaboration.', features:['Unlimited blocks','File uploads','30-day page history'],
    variants: [{name:'1 Month', price:'₹1,999', priceNum:1999}]},
  {id:'nordvpn',name:'NordVPN',cat:'Softwares & Tools',mrp:'₹2,999',discount:'80%',icon:'nordvpn',tag:null,color:'#4687FF',
    desc:'NordVPN for secure, private browsing with global servers.', features:['5500+ servers','No-logs policy','High speed'],
    variants: [{name:'3 Months', price:'₹599', priceNum:599}, {name:'6 Months', price:'₹1,499', priceNum:1499}, {name:'12 Months', price:'₹1,999', priceNum:1999}]},
  {id:'expressvpn',name:'ExpressVPN',cat:'Softwares & Tools',mrp:'₹1,999',discount:'76%',icon:'expressvpn',tag:null,color:'#0F866C',
    desc:'ExpressVPN. Connect up to 8 Devices, 105+ Countries Servers, Premium Encryption.', features:['105+ Countries','8 Devices','Lightning-Fast Speed'],
    variants: [{name:'1 Month', price:'₹479', priceNum:479}]},
  {id:'windows11',name:'Windows 11 Pro',cat:'Softwares & Tools',mrp:'₹9,999',discount:'92%',icon:'windows11',tag:'Popular',color:'#0078D4',
    desc:'Windows 11 Pro Official License Key. Private, Secure Login, and Full Warranty.', features:['Official License Key','Lifetime (Retail)','Full Warranty'],
    variants: [{name:'Lifetime', price:'₹719', priceNum:719}]},
  {id:'filmora',name:'Filmora Premium',cat:'Softwares & Tools',mrp:'₹4,999',discount:'50%',icon:'filmora',tag:null,color:'#00D2D3',
    desc:'Wondershare Filmora premium video editing software. 100% Official & Legit Subscription.', features:['No watermark','Full Access','Complete Warranty'],
    variants: [{name:'Filmora 13/14 (1 Year)', price:'₹2,279', priceNum:2279}]},
  {id:'lenskart',name:'Lenskart Gold',cat:'Softwares & Tools',mrp:'₹999',discount:'80%',icon:'lenskart',tag:null,color:'#32b8a4',
    desc:'Lenskart Gold membership for Buy 1 Get 1 Free offers.', features:['BOGO offers','Free eye checkup','Premium support'],
    variants: [{name:'Gold Max', price:'₹249', priceNum:249}]},
  {id:'coursera',name:'Coursera Plus',cat:'Softwares & Tools',mrp:'₹3,999',discount:'75%',icon:'coursera',tag:null,color:'#0056D2',
    desc:'Coursera Plus access to 7000+ courses and certifications.', features:['Unlimited courses','Certificates included','Top universities'],
    variants: [{name:'1 Year', price:'₹1,299', priceNum:1299}]},
  {id:'infosys',name:'Infosys Certifications',cat:'Certifications',mrp:'₹4,999',discount:'86%',icon:'infosys',tag:null,color:'#007CC3',
    desc:'Permanent Access to legitimate Infosys Certifications in PDF format with QR. Available in:<ul><li>CSS 3 & JavaScript</li><li>Data Science & AI</li><li>IoT & Cloud Computing</li><li>Java, Python & C++</li><li>Business Communication</li><li>DSA & RPA</li><li>Cyber Security & Information Security</li><li>Angular, R, Node.js & Software Engineering</li><li>Ethical AI & AZ-900 Azure</li></ul>', features:['Permanent validity','QR verifiable','Delivery in 1 day'],
    variants: [{name:'Permanent Access', price:'₹699', priceNum:699}]},
  {id:'jpmorgan',name:'JPMorgan Certifications',cat:'Certifications',mrp:'₹4,999',discount:'86%',icon:'jpmorgan',tag:null,color:'#4A2D00',
    desc:'Permanent Access to legitimate JPMorgan Certifications in PDF format with QR. Available in:<ul><li>Investment Banking & Commercial Banking</li><li>Asset Management & Global Finance</li><li>Markets & Global Private Banks</li><li>CADP & AADP</li><li>Excel Skills & Agile</li><li>Software Engineering & Cybersecurity</li><li>Quantitative Research</li><li>Internal Audit</li></ul>', features:['Permanent validity','QR verifiable','Delivery in 1 day'],
    variants: [{name:'Permanent Access', price:'₹699', priceNum:699}]},
  {id:'pocketfm',name:'Pocket FM VIP',cat:'Softwares & Tools',mrp:'₹999',discount:'90%',icon:'pocketfm',tag:null,color:'#E50914',
    desc:'Pocket FM VIP subscription for unlimited audiobooks.', features:['Ad-free listening','All audiobooks unlocked','Offline downloads'],
    variants: [{name:'1 Month', price:'₹119', priceNum:119}]},

  // --- Social Media Growth (+20%) ---
  {id:'ig-follower',name:'Instagram Follower',cat:'Social Media Growth',mrp:'₹9,999',discount:'97%',icon:'instagram',tag:'Hot Deal',color:'#E1306C',
    desc:'Boost your Instagram presence with organic-looking followers.', features:['Fast delivery','Non-drop guarantee','High quality profiles'],
    variants: [
      {name:'1000 Follower', price:'₹299', priceNum:299}, {name:'5000 Follower', price:'₹1,299', priceNum:1299},
      {name:'10000 Follower', price:'₹1,999', priceNum:1999}, {name:'20000 Follower', price:'₹3,899', priceNum:3899},
      {name:'100000 Follower (100k)', price:'₹15,999', priceNum:15999}
    ]},
  {id:'1m-reels',name:'1 Million Reels Views',cat:'Social Media Growth',mrp:'₹9,999',discount:'90%',icon:'reels',tag:'Popular',color:'#E1306C',
    desc:'Go viral with 1 Million views on your Instagram Reel.', features:['Viral push','High retention','Safe & secure'],
    variants: [{name:'Standard', price:'₹999', priceNum:999}]},
  {id:'reels-views',name:'Reels Views',cat:'Social Media Growth',mrp:'₹9,999',discount:'99%',icon:'reels',tag:null,color:'#E1306C',
    desc:'Get targeted views for your Instagram reels.', features:['Instant start','Real engagement','Affordable'],
    variants: [
      {name:'1k Views', price:'₹15', priceNum:15}, {name:'5k Views', price:'₹49', priceNum:49}, {name:'10k Views', price:'₹89', priceNum:89},
      {name:'20k Views', price:'₹175', priceNum:175}, {name:'50k Views', price:'₹299', priceNum:299}, {name:'100k Views', price:'₹499', priceNum:499},
      {name:'500k Views', price:'₹1,799', priceNum:1799}, {name:'1 million Views', price:'₹2,599', priceNum:2599}
    ]},
  {id:'ig-likes-real',name:'Instagram Likes ( Real)',cat:'Social Media Growth',mrp:'₹999',discount:'92%',icon:'instagram',tag:null,color:'#E1306C',
    desc:'Real likes from active accounts to boost post engagement.', features:['Active accounts','Algorithm boost','Fast delivery'],
    variants: [
      {name:'100 Likes', price:'₹75', priceNum:75}, {name:'300 Likes', price:'₹149', priceNum:149}, {name:'500 Likes', price:'₹199', priceNum:199},
      {name:'1000 Likes', price:'₹299', priceNum:299}, {name:'5000 Likes', price:'₹1,199', priceNum:1199}, {name:'10000 Likes', price:'₹1,499', priceNum:1499}
    ]},
  {id:'ig-likes-bot',name:'Instagram Likes (Bot Likes)',cat:'Social Media Growth',mrp:'₹499',discount:'95%',icon:'instagram',tag:null,color:'#E1306C',
    desc:'Cheap bot likes to increase your post numbers quickly.', features:['Instant delivery','High volume','Lowest price'],
    variants: [
      {name:'100 Likes', price:'₹25', priceNum:25}, {name:'300 Likes', price:'₹49', priceNum:49}, {name:'500 Likes', price:'₹85', priceNum:85},
      {name:'1000 Likes (1k)', price:'₹129', priceNum:129}, {name:'5000 Likes (5k)', price:'₹299', priceNum:299}, {name:'10000 Likes (10k)', price:'₹499', priceNum:499},
      {name:'50000 Likes (50k)', price:'₹1,999', priceNum:1999}, {name:'100000 Likes (100k)', price:'₹2,999', priceNum:2999}
    ]},

  // --- Digital Bundles (+40%) ---
  {id:'cb-bundle-0',name:'Animated Dancing Bundle',cat:'Digital Bundles',mrp:'₹999',discount:'95%',icon:'cb-bundle-0',tag:null,color:'#6366f1',
    desc:'Premium digital bundle for social media growth. Ready to use and highly engaging.', features:['HD Quality','Ready to Use','Instant Access'],
    variants: [{name:'Full Bundle', price:'₹59', priceNum:59}]},
  {id:'cb-bundle-1',name:'AI Hulk Reel',cat:'Digital Bundles',mrp:'₹999',discount:'95%',icon:'cb-bundle-1',tag:null,color:'#6366f1',
    desc:'Premium digital bundle for social media growth. Ready to use and highly engaging.', features:['HD Quality','Ready to Use','Instant Access'],
    variants: [{name:'Full Bundle', price:'₹119', priceNum:119}]},
  {id:'cb-bundle-2',name:'Monkey Vlogging Bundle',cat:'Digital Bundles',mrp:'₹999',discount:'95%',icon:'cb-bundle-2',tag:null,color:'#6366f1',
    desc:'Premium digital bundle for social media growth. Ready to use and highly engaging.', features:['HD Quality','Ready to Use','Instant Access'],
    variants: [{name:'Full Bundle', price:'₹119', priceNum:119}]},
  {id:'cb-bundle-3',name:'All In One Bundle',cat:'Digital Bundles',mrp:'₹999',discount:'95%',icon:'cb-bundle-3',tag:null,color:'#6366f1',
    desc:'Premium digital bundle for social media growth. Ready to use and highly engaging.', features:['HD Quality','Ready to Use','Instant Access'],
    variants: [{name:'Full Bundle', price:'₹1199', priceNum:1199}]},
  {id:'cb-bundle-4',name:'Shopify 500+ Themes',cat:'Digital Bundles',mrp:'₹999',discount:'95%',icon:'cb-bundle-4',tag:null,color:'#6366f1',
    desc:'Premium digital bundle for social media growth. Ready to use and highly engaging.', features:['HD Quality','Ready to Use','Instant Access'],
    variants: [{name:'Full Bundle', price:'₹119', priceNum:119}]},
  {id:'cb-bundle-5',name:'Ben 10 Bundle',cat:'Digital Bundles',mrp:'₹999',discount:'95%',icon:'cb-bundle-5',tag:null,color:'#6366f1',
    desc:'Premium digital bundle for social media growth. Ready to use and highly engaging.', features:['HD Quality','Ready to Use','Instant Access'],
    variants: [{name:'Full Bundle', price:'₹59', priceNum:59}]},
  {id:'cb-bundle-6',name:'Oggy and Cockroaches',cat:'Digital Bundles',mrp:'₹999',discount:'95%',icon:'cb-bundle-6',tag:null,color:'#6366f1',
    desc:'Premium digital bundle for social media growth. Ready to use and highly engaging.', features:['HD Quality','Ready to Use','Instant Access'],
    variants: [{name:'Full Bundle', price:'₹59', priceNum:59}]},
  {id:'cb-bundle-7',name:'Mr. Bean Bundle',cat:'Digital Bundles',mrp:'₹999',discount:'95%',icon:'cb-bundle-7',tag:null,color:'#6366f1',
    desc:'Premium digital bundle for social media growth. Ready to use and highly engaging.', features:['HD Quality','Ready to Use','Instant Access'],
    variants: [{name:'Full Bundle', price:'₹59', priceNum:59}]},
  {id:'cb-bundle-8',name:'Doraemon Bundle Pack',cat:'Digital Bundles',mrp:'₹999',discount:'95%',icon:'cb-bundle-8',tag:null,color:'#6366f1',
    desc:'Premium digital bundle for social media growth. Ready to use and highly engaging.', features:['HD Quality','Ready to Use','Instant Access'],
    variants: [{name:'Full Bundle', price:'₹59', priceNum:59}]},
  {id:'cb-bundle-9',name:'Motivational Money Bundle',cat:'Digital Bundles',mrp:'₹999',discount:'95%',icon:'cb-bundle-9',tag:null,color:'#6366f1',
    desc:'Premium digital bundle for social media growth. Ready to use and highly engaging.', features:['HD Quality','Ready to Use','Instant Access'],
    variants: [{name:'Full Bundle', price:'₹59', priceNum:59}]},
  {id:'cb-bundle-10',name:'Bageshwar Baba Pack',cat:'Digital Bundles',mrp:'₹999',discount:'95%',icon:'cb-bundle-10',tag:null,color:'#6366f1',
    desc:'Premium digital bundle for social media growth. Ready to use and highly engaging.', features:['HD Quality','Ready to Use','Instant Access'],
    variants: [{name:'Full Bundle', price:'₹59', priceNum:59}]},
  {id:'cb-bundle-11',name:'Anime Quotes Pack',cat:'Digital Bundles',mrp:'₹999',discount:'95%',icon:'cb-bundle-11',tag:null,color:'#6366f1',
    desc:'Premium digital bundle for social media growth. Ready to use and highly engaging.', features:['HD Quality','Ready to Use','Instant Access'],
    variants: [{name:'Full Bundle', price:'₹59', priceNum:59}]},
  {id:'cb-bundle-12',name:'Luxury Watches Reel Pack',cat:'Digital Bundles',mrp:'₹999',discount:'95%',icon:'cb-bundle-12',tag:null,color:'#6366f1',
    desc:'Premium digital bundle for social media growth. Ready to use and highly engaging.', features:['HD Quality','Ready to Use','Instant Access'],
    variants: [{name:'Full Bundle', price:'₹59', priceNum:59}]},
  {id:'cb-bundle-13',name:'Space Reels Bundle',cat:'Digital Bundles',mrp:'₹999',discount:'95%',icon:'cb-bundle-13',tag:null,color:'#6366f1',
    desc:'Premium digital bundle for social media growth. Ready to use and highly engaging.', features:['HD Quality','Ready to Use','Instant Access'],
    variants: [{name:'Full Bundle', price:'₹59', priceNum:59}]},
  {id:'bundle-creators',name:"Creator's Vault 2025",cat:'Digital Bundles',mrp:'₹4,999',discount:'97%',icon:'bundle-creators',tag:'Hot Deal',color:'#6366f1',
    desc:'The ultimate creator toolkit — everything you need in one bundle.', features:['All-in-one vault','Premium assets','2025 edition'],
    variants: [{name:'Full Bundle', price:'₹139', priceNum:139}]},
  {id:'bundle-podcast',name:'Podcast Reel Bundle',cat:'Digital Bundles',mrp:'₹999',discount:'95%',icon:'bundle-podcast',tag:null,color:'#6366f1',
    desc:'Podcast-style reels with trending formats for social media.', features:['Podcast format','Viral clips','High retention'],
    variants: [{name:'Full Bundle', price:'₹69', priceNum:69}]},
  {id:'bundle-space',name:'Space Reels Bundle',cat:'Digital Bundles',mrp:'₹999',discount:'95%',icon:'bundle-space',tag:null,color:'#6366f1',
    desc:'Stunning space and universe themed reel content.', features:['Space visuals','Cinematic quality','Viral potential'],
    variants: [{name:'Full Bundle', price:'₹69', priceNum:69}]},
  {id:'bundle-f1',name:'F1 Cars Bundle',cat:'Digital Bundles',mrp:'₹999',discount:'95%',icon:'bundle-f1',tag:null,color:'#6366f1',
    desc:'Formula 1 cars and racing clips for car enthusiast reels.', features:['F1 footage','High quality','Trending niche'],
    variants: [{name:'Full Bundle', price:'₹69', priceNum:69}]},
  {id:'bundle-gym',name:'Gym Motivational Bundle',cat:'Digital Bundles',mrp:'₹999',discount:'95%',icon:'bundle-gym',tag:null,color:'#6366f1',
    desc:'Gym motivation, workout clips and fitness content.', features:['Workout clips','Motivational quotes','Fitness niche'],
    variants: [{name:'Full Bundle', price:'₹69', priceNum:69}]},
  {id:'bundle-emotional',name:'Emotional Reels Bundle',cat:'Digital Bundles',mrp:'₹999',discount:'95%',icon:'bundle-emotional',tag:null,color:'#6366f1',
    desc:'Emotional and heartfelt video clips for viral storytelling.', features:['Emotional content','Story format','High engagement'],
    variants: [{name:'Full Bundle', price:'₹69', priceNum:69}]},

  // --- OTT Apps ---
  {id:'youtube-premium',name:'YouTube Premium',cat:'OTT Apps',mrp:'₹599',discount:'83%',icon:'youtube',tag:null,color:'#FF0000',
    desc:'YouTube Premium for ad-free videos and background play.', features:['Ad-free videos','Background play','YouTube Music'],
    variants: [{name:'Shared Plan', price:'₹99', priceNum:99}, {name:'Private Account', price:'₹199', priceNum:199}]},
];

export const categories = ['All','AI Tools','Certifications','Softwares & Tools','Developer Tools','Design Resources','Social Media Growth','Digital Bundles','OTT Apps'];
